### ISSUE TITLE
Why not publish to npm registry?

### ISSUE THREAD

**Issue by yugasun** [virtualeconomy/js-v-min-sdk#1]
Normally, blockchain sdk project will publish their npm module to [npm registry](https://www.npmjs.com/), why don't this project publish?

**Comment by SheldonYS** [comment]
This is not full version of SDK repo that only for exchange used. It will be deprecated once another repo named `js-v-sdk` is completed. The `js-v-sdk` is still developing in progress and will be open source soon.

**Comment by yugasun** [comment]
Well, it's very unfriendly for module using.

**Comment by SheldonYS** [comment]
Yes. However, as you know, the SDK can be used as wallet, so we are facing the security issue and need time to go through the fully test for few month. It may have some inconvenience during this period because we do not want to spread and promote this SDK too fast. After we ensure another repo named `js-v-sdk` stable and security, we will put it on npm.

**Comment by yugasun** [comment]
Got it, thanks for your reply.

**Comment by SheldonYS** [comment]
Thanks for your understanding.

**Comment by yugasun** [comment]
Refer to #2
